.PHONY: clean All

All:
	@echo "----------Building project:[ 99-Section-Challenge - Debug ]----------"
	@cd "99-Section-Challenge" && "$(MAKE)" -f  "99-Section-Challenge.mk"
clean:
	@echo "----------Cleaning project:[ 99-Section-Challenge - Debug ]----------"
	@cd "99-Section-Challenge" && "$(MAKE)" -f  "99-Section-Challenge.mk" clean
