.PHONY: clean All

All:
	@echo "----------Building project:[ 51-Section-Challenge - Debug ]----------"
	@cd "51-Section-Challenge" && "$(MAKE)" -f  "51-Section-Challenge.mk"
clean:
	@echo "----------Cleaning project:[ 51-Section-Challenge - Debug ]----------"
	@cd "51-Section-Challenge" && "$(MAKE)" -f  "51-Section-Challenge.mk" clean
