.PHONY: clean All

All:
	@echo "----------Building project:[ 48-What-Is-The-Size-Of-A-Variable - Debug ]----------"
	@cd "48-What-Is-The-Size-Of-A-Variable" && "$(MAKE)" -f  "48-What-Is-The-Size-Of-A-Variable.mk"
clean:
	@echo "----------Cleaning project:[ 48-What-Is-The-Size-Of-A-Variable - Debug ]----------"
	@cd "48-What-Is-The-Size-Of-A-Variable" && "$(MAKE)" -f  "48-What-Is-The-Size-Of-A-Variable.mk" clean
