.PHONY: clean All

All:
	@echo "----------Building project:[ 78-If-Else-Statement - Debug ]----------"
	@cd "78-If-Else-Statement" && "$(MAKE)" -f  "78-If-Else-Statement.mk"
clean:
	@echo "----------Cleaning project:[ 78-If-Else-Statement - Debug ]----------"
	@cd "78-If-Else-Statement" && "$(MAKE)" -f  "78-If-Else-Statement.mk" clean
