.PHONY: clean All

All:
	@echo "----------Building project:[ 90-Section-Challenge - Debug ]----------"
	@cd "90-Section-Challenge" && "$(MAKE)" -f  "90-Section-Challenge.mk"
clean:
	@echo "----------Cleaning project:[ 90-Section-Challenge - Debug ]----------"
	@cd "90-Section-Challenge" && "$(MAKE)" -f  "90-Section-Challenge.mk" clean
