.PHONY: clean All

All:
	@echo "----------Building project:[ 122-The-Relationship-Between-Arrays-And-Pointers - Debug ]----------"
	@cd "122-The-Relationship-Between-Arrays-And-Pointers" && "$(MAKE)" -f  "122-The-Relationship-Between-Arrays-And-Pointers.mk"
clean:
	@echo "----------Cleaning project:[ 122-The-Relationship-Between-Arrays-And-Pointers - Debug ]----------"
	@cd "122-The-Relationship-Between-Arrays-And-Pointers" && "$(MAKE)" -f  "122-The-Relationship-Between-Arrays-And-Pointers.mk" clean
