.PHONY: clean All

All:
	@echo "----------Building project:[ 119-Assessing-Pointers - Debug ]----------"
	@cd "119-Assessing-Pointers" && "$(MAKE)" -f  "119-Assessing-Pointers.mk"
clean:
	@echo "----------Cleaning project:[ 119-Assessing-Pointers - Debug ]----------"
	@cd "119-Assessing-Pointers" && "$(MAKE)" -f  "119-Assessing-Pointers.mk" clean
