.PHONY: clean All

All:
	@echo "----------Building project:[ 123-Pointer-Arithmetic - Debug ]----------"
	@cd "123-Pointer-Arithmetic" && "$(MAKE)" -f  "123-Pointer-Arithmetic.mk"
clean:
	@echo "----------Cleaning project:[ 123-Pointer-Arithmetic - Debug ]----------"
	@cd "123-Pointer-Arithmetic" && "$(MAKE)" -f  "123-Pointer-Arithmetic.mk" clean
