.PHONY: clean All

All:
	@echo "----------Building project:[ 42-Basic-Input-And-Output-Using-Cin-And-Cout - Debug ]----------"
	@cd "42-Basic-Input-And-Output-Using-Cin-And-Cout" && "$(MAKE)" -f  "42-Basic-Input-And-Output-Using-Cin-And-Cout.mk"
clean:
	@echo "----------Cleaning project:[ 42-Basic-Input-And-Output-Using-Cin-And-Cout - Debug ]----------"
	@cd "42-Basic-Input-And-Output-Using-Cin-And-Cout" && "$(MAKE)" -f  "42-Basic-Input-And-Output-Using-Cin-And-Cout.mk" clean
