.PHONY: clean All

All:
	@echo "----------Building project:[ 60-Section-Challenge - Debug ]----------"
	@cd "60-Section-Challenge" && "$(MAKE)" -f  "60-Section-Challenge.mk"
clean:
	@echo "----------Cleaning project:[ 60-Section-Challenge - Debug ]----------"
	@cd "60-Section-Challenge" && "$(MAKE)" -f  "60-Section-Challenge.mk" clean
