.PHONY: clean All

All:
	@echo "----------Building project:[ 109-Pass-By-Reference - Debug ]----------"
	@cd "109-Pass-By-Reference" && "$(MAKE)" -f  "109-Pass-By-Reference.mk"
clean:
	@echo "----------Cleaning project:[ 109-Pass-By-Reference - Debug ]----------"
	@cd "109-Pass-By-Reference" && "$(MAKE)" -f  "109-Pass-By-Reference.mk" clean
