.PHONY: clean All

All:
	@echo "----------Building project:[ 114-Section-Challenge - Debug ]----------"
	@cd "114-Section-Challenge" && "$(MAKE)" -f  "114-Section-Challenge.mk"
clean:
	@echo "----------Cleaning project:[ 114-Section-Challenge - Debug ]----------"
	@cd "114-Section-Challenge" && "$(MAKE)" -f  "114-Section-Challenge.mk" clean
