.PHONY: clean All

All:
	@echo "----------Building project:[ 113-Recursive-Functions - Debug ]----------"
	@cd "113-Recursive-Functions" && "$(MAKE)" -f  "113-Recursive-Functions.mk"
clean:
	@echo "----------Cleaning project:[ 113-Recursive-Functions - Debug ]----------"
	@cd "113-Recursive-Functions" && "$(MAKE)" -f  "113-Recursive-Functions.mk" clean
