.PHONY: clean All

All:
	@echo "----------Building project:[ 74-Section-Challenge - Debug ]----------"
	@cd "74-Section-Challenge" && "$(MAKE)" -f  "74-Section-Challenge.mk"
clean:
	@echo "----------Cleaning project:[ 74-Section-Challenge - Debug ]----------"
	@cd "74-Section-Challenge" && "$(MAKE)" -f  "74-Section-Challenge.mk" clean
